name: Workflow Integration Testing

on:
  pull_request: #pull request on main
    branches: [ main ]

env:
  PRODUCT_VERSION: "latest"

jobs:
  build_and_test_java:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: userdata
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        working-directory: ./webapplication
        run: mvn clean install
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: Initialize Packer Init
        working-directory: ./AMI
        run: packer init .
      - name: Packer Format Check
        working-directory: ./AMI
        run: packer fmt -check .

      - name: Packer Template Validate
        working-directory: ./AMI
        run: packer validate .

